name: CI/CD Pipeline

env:
  SERVICE_NAME: rag-fastapi-app
  UV_LINK_MODE: copy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    name: Run Quality Checks
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:python3.11-bookworm-slim

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install make
        run: apt-get update && apt-get install -y make

      - name: Install dependencies
        run: make setup

      - name: Lint Fix
        run: make lint.fix

      - name: Lint Check
        run: make lint.check

      - name: Type Check
        run: make type.check

      - name: Run Unit Tests with Coverage
        run: make test

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: .test_results/coverage.xml

      - name: Dockerfile Check
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  build-and-publish:
    needs: checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # needed for the docker/build-push-action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:v0.13.2

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:latest
